### ISSUE TITLE
Rework and simplify the binding layer.

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/iotjs#1201]
The current binding layer was intended to make it possible to use other JS engines, but the IoT.js currently strictly depends on JerryScript. By simplifying the binding layer we could reduce the binary size and improve the performance of the IoT.js framework. It would be a huge rework, but it definitely worth to take the effort.  I suggest to do it incrementally in smaller steps.

  1. [x] Change the `iotjs_jval_t` to `jerry_value_t` (currently it is a struct) ~#1200~
  2. [x] Change the `iotjs_jval_t*` occurrences to `iotjs_jval_t` (It could be done incrementally in smaller patches)  ~#1209~ ~#1213~ ~#1223~  ~#1226~ ~#1227~ ~#1228~ ~#1231~ ~#1239~ ~#1240~ ~#1242~ ~#1243~ ~#1244~ ~#1248~ ~#1249~ ~#1250~ ~#1253~ ~#1254~ ~#1260~ ~#1261~ ~#1265~ ~#1271~ ~#1279~
  3. [x] Remove the `iotjs_jval_t` typedef and use `jerry_value_t` directly in the whole code base. ~#1364~
  4. [x] Remove the unnecessary binding functions and call the JerryScript API functions directly. (It could be done incrementally in smaller patches) ~#1290~ ~#1293~ ~#1296~ ~#1335~ ~#1388~

I've already proposed a PR for the first step.

**Comment by yichoi** [comment]
It makes sense. Thanks

**Comment by zherczeg** [comment]
I support this rework. Snapshots, magic strings and other convenience features are highly JerryScript dependant, so it does not make sense to try to support other engines.

**Comment by daeyeon** [comment]
I think that you mean not `iotjs_val_t`, but `iotjs_jval_t`.

**Comment by LaszloLango** [comment]
@daeyeon yes, I updated the description.

**Comment by daeyeon** [comment]
@LaszloLango can you kindly explain why `Change the iotjs_jval_t* occurrences to iotjs_jval_t (It could be done incrementally in smaller patches)` is needed?

**Comment by LaszloLango** [comment]
@daeyeon The goal is to use only `jerry_value_t` at the end. It is an `uint32_t`, so it is unnecessary to use 32/64 bit pointers to pass it to any function. It is better to use as a value, so we can save the dereference operations which should improve the IoT.js performance. Furthermore the memory consumption won't be changed on 32 bit systems. (Memory consumption will be reduced on 64 bit systems, because we will use 32 unsigned integers instead of 64 bit pointers, but it is not a big gain for use, because 64 bit system are not our main target.)

**Comment by zherczeg** [comment]
Yes, we can remove all de-references (memory loads) and do not need to store values on stack just to provide a pointer to them.

**Comment by LaszloLango** [comment]
IMHO this task is completed. Many PRs landed for this and the code is much cleaner now.  I close this issue. Feel free to reopen if you think there are more things to do here.
