### ISSUE TITLE
NuttX build and run simple hello world

### ISSUE THREAD

**Issue by seanshpark** [Samsung/iotjs#53]
NuttX build with current iotjs, run simple hello world script.

* [x] include jerry math lib 
    * [x] https://github.com/Samsung/iotjs/pull/51
    * [x] https://github.com/Samsung/iotjs/pull/52 > drop
    * [x] https://github.com/Samsung/iotjs/issues/55
    
* [ ] fix "out of memory" problem
    * grow jerry heap size: https://github.com/Samsung/jerryscript/commit/a28d03aba7fcb543c538e70e11f389ad015a6b9f
   * [x] https://github.com/Samsung/jerryscript/issues/103 (Issue, Question about mem_stats)
   * [x] https://github.com/Samsung/jerryscript/issues/109 (Issue, API for expanding Magic string)
   * [ ] https://github.com/Samsung/jerryscript/issues/111 (Issue, Byte code snap-shot to save runtime heap)
   * [x] https://github.com/Samsung/jerryscript/pull/136 (PR, New External Magic String API to save heap memory) 
   * [x] register magic strings of iotjs
* [x] prepare very simple test script
````
console.log("Hello IoT.js");
````

**Comment by ILyoan** [comment]
I think this can be close now.
Feel free to reopen if needed.
